version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm test
    build:
      commands:
        - env | grep -e MY_APP_DATABASE_URL >> .env.production
        - env | grep -e NEXTAUTH_ >> .env.production
        - npx prisma generate
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
