version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next # Specify where the build output is located
    files:
      - '**/*'
  cache:
    paths:
