version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: local-mysql
    restart: always
    ports:
      - '3308:3306' # Expose MySQL on localhost:3308
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql_data:/var/lib/mysql # Persist data between container restarts
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
