'use client';

import { useState } from 'react';
import { Task } from '@/lib/db';
import { useTaskStore } from '@/lib/store/task';
const AddTasks = () => {
  const { addTask } = useTaskStore();
  const [taskText, setTaskText] = useState('');

  const handleAddTask = async () => {
    const newTask: Task = {
      id: '', // generated by the task service
      text: taskText,
      completed: false,
      dateAdded: new Date(),
      dateUpdated: new Date(),
    };

    await addTask(newTask);
    setTaskText('');
  };

  return (
    <div className="flex items-center border rounded-full px-4 py-2 bg-gray-100 space-x-2">
      <input
        id="task"
        type="text"
        value={taskText}
        onChange={(e) => setTaskText(e.target.value)}
        className="flex-grow bg-transparent outline-none placeholder-gray-500"
        placeholder="Add a task..."
      />
      <button onClick={handleAddTask}>Add</button>
    </div>
  );
};

export default AddTasks;
